### ISSUE TITLE
Decimals and letters

### ISSUE THREAD

**Issue by wlayton** [rayvoelker/js-loc-callnumbers#1]
I found two small issues with the isBetween method, which I believe has to do with how the call number is normalized in returnNormLcCall.

First, letters aren't right-padded up to the 3 positions. For example, a call number starting with a single "D" will be sorted before a call number starting with "AA", which isn't correct.

Second, numbers after a decimal point aren't placed into a separate field during normalization. The result is that Z 39.50 will be sorted after Z 50, which again isn't correct.

Thanks for this software!

**Comment by rayvoelker** [comment]
Thanks for the feedback on the incorrect normalization returned from the returnNormLcCall method.

You're absolutely correct about the call numbers with a single letter vs. multiple letters. It looks like the the problem is in the padding function for the start of the call number.

```
AA gets padded out as 0000000AA
D  gets padded out as 00000000D
```

It looks like I'll have to fix the padding function to do a left or right padding depending on the position of the call number being padded. They should look like the following ...

```
AA gets padded out as AA0000000
D  gets padded out as D00000000
```

---

I'd like to also mention that in the readme.md file that the regular expression that parses the call number has been adapted from the work of several other developers (linked to in the readme if you want to go check them out), and has some very odd behavior (some of which you've noted) at times.  It's been a goal of mine with this project to work out some other type of algorithm that _doesn't_ use regular expressions. In addition, I think that maybe the practice of padding the call number with "0" for the normalized value isn't the best approach, as it creates a less human-readable normalized call number. I'm not sure if you're familiar with Innovative products, but I like the way that their normalization algorithm outputs the normalized call numbers for storage in the database. Below is an example of sorted normalized call numbers coming out of our catalog system.

```
AS  911 A2 F652
AY   81 R6 N3
B   765 D73 Z83 1988
BF   31 A65 2007
BQ 9259 B37 2002
BS  192.2 A1 1964 G3 V   31 1998
D     5 M55 2007
PR   85 B688
Y     3 T 22 2 2 H 34 7
```

The way that these are formatted or nice for several reasons. 
1) They're easy to read, and line up nicely in a spreadsheet 
2) They certainly take up less room in a database than the "0" padded results 
3) String sorting functions of major databases sort them correctly.

I would like to re-write the normalization function of this class to produce similar results. Let me know if you have any ideas!

--Ray
