### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by geocolumbus** [rayvoelker/js-loc-callnumbers#3]
Hi,

I downloaded and ran the locCallClass. I ran the quick_example and ran into this javascript error:

<pre>
locCallClass.js:72 Uncaught TypeError: callnumbers.sort is not a function
    at locCallClass.sortCallNumbers (locCallClass.js:72)
    at quick_example.html:74
</pre>

Which occurs when you make this call (inside of quick_example.html)

<pre>
var sorted = loc.sortCallNumbers("HA 203 .A218 no.54", "H 1 .E77 v.1 1976", "HB 501 .M5 A76 1990");
</pre>

I think you need to add square brackets to pass an array of objects, like this:

<pre>
var sorted = loc.sortCallNumbers(["HA 203 .A218 no.54", "H 1 .E77 v.1 1976", "HB 501 .M5 A76 1990"]);
</pre>

Cheers!

**Comment by rayvoelker** [comment]
Thanks for discovering that.

I was going back and forth about if I should remove that function from the class or not... It's probably much more useful to use the function of this class, "localeCompare" which sort of mimics the javascript string function of the same name.... so that you could use it in as a sort function outside of the class. Here's an example.

```
var test_data = ["E 876 .U84 1986","TA1520.W35 1998","E 487 .C746","DT 636 .S5 A3","Q183.9.L45 1993","DS 917.35 .P33","E184.A1I444 1992","DC130.A2 H3","TD 741 .I33","TP 155 .C74 1986","E 487 .C746 1966"]
var loc = new locCallClass
console.log(test_data);
test_data.sort(function(a,b){
  return loc.localeCompare(a,b)
});
console.log(test_data);
```

so test_data becomes :

```
["DC130.A2 H3","DS 917.35 .P33","DT 636 .S5 A3","E184.A1I444 1992","E 487 .C746","E 487 .C746 1966","E 876 .U84 1986","Q183.9.L45 1993","TA1520.W35 1998","TD 741 .I33,TP 155 .C74 1986"]
```
